import type { MockEvent } from "./types";

export const MOCK_EVENTS: MockEvent[] = [
  {
    id: "e1",
    title: "Nils Frahm — All Encores Tour",
    category: "music",
    venue: { id: "v1", name: "Aula UAM", address: "Wieniawskiego 1" },
    imageUrl: "/mock/event-1.jpg",
    date: "Sob, 24 maja",
    time: "20:00",
    startDate: "2026-05-24T20:00:00",
    priceFrom: 189,
    lat: 52.4083,
    lng: 16.9172,
    description:
      "Niemiecki kompozytor i pianista po raz pierwszy w Poznaniu. Dwie godziny improwizacji na fortepianie, syntezatorach i organach.",
    badges: ["fast"],
    city: "poznan",
  },
  {
    id: "e2",
    title: "Smolik / Kev Fox — Solidarni z Ukrainą",
    category: "music",
    venue: { id: "v2", name: "Tama", address: "Szyperska 3" },
    imageUrl: "/mock/event-2.jpg",
    date: "Sob, 24 maja",
    time: "21:30",
    startDate: "2026-05-24T21:30:00",
    priceFrom: 129,
    lat: 52.4119,
    lng: 16.9305,
    description:
      "Smolik i Kev Fox spotykają się na scenie po raz pierwszy w tym roku. Cały dochód z biletów trafia do Fundacji Pomocy Ukrainie.",
    badges: ["live"],
    city: "poznan",
  },
  {
    id: "e3",
    title: "Techno Tuesday: Recondite (live)",
    category: "nightlife",
    venue: { id: "v3", name: "SQ Klub", address: "Wenecjańska 9" },
    imageUrl: "/mock/event-3.jpg",
    date: "Wt, 27 maja",
    time: "23:00",
    startDate: "2026-05-27T23:00:00",
    priceFrom: 80,
    lat: 52.4025,
    lng: 16.9198,
    description:
      "Cotygodniowa noc techno w SQ. Tym razem na żywo Recondite — mistrz minimalistycznego, melancholijnego brzmienia.",
    badges: ["recur"],
    city: "poznan",
  },
  {
    id: "e4",
    title: "Wystawa: Wojciech Fangor — Powierzchnie",
    category: "arts_culture",
    venue: {
      id: "v4",
      name: "Muzeum Narodowe",
      address: "Aleje Marcinkowskiego 9",
    },
    imageUrl: "/mock/event-4.jpg",
    date: "Codziennie do 30 cze",
    time: "10:00–18:00",
    startDate: "2026-05-25T10:00:00",
    priceFrom: 0,
    lat: 52.408,
    lng: 16.9245,
    description:
      "Retrospektywa jednego z najważniejszych polskich artystów XX wieku. 60 obrazów, instalacja site-specific.",
    badges: ["free"],
    city: "poznan",
  },
  {
    id: "e5",
    title: "Lech vs Legia — Ekstraklasa",
    category: "sport_fitness",
    venue: { id: "v5", name: "Stadion Poznań", address: "Bułgarska 17" },
    imageUrl: "/mock/event-5.jpg",
    date: "Nd, 25 maja",
    time: "17:30",
    startDate: "2026-05-25T17:30:00",
    priceFrom: 65,
    lat: 52.3942,
    lng: 16.8858,
    description: "Derby z Legią o utrzymanie pozycji w czołówce.",
    badges: ["fast"],
    city: "poznan",
  },
  {
    id: "e6",
    title: "Open'er Festival 2026 — pre-party",
    category: "festival",
    venue: {
      id: "v6",
      name: "Skwer Modra Mleczarnia",
      address: "Stary Rynek 84",
    },
    imageUrl: "/mock/event-6.jpg",
    date: "Pt, 30 maja",
    time: "19:00",
    startDate: "2026-05-30T19:00:00",
    priceFrom: 0,
    lat: 52.4082,
    lng: 16.9338,
    description:
      "Oficjalna rozgrzewka przed Open'er 2026. DJ-e z line-upu, food trucki, wystawa fotograficzna.",
    badges: ["free"],
    city: "poznan",
  },
  {
    id: "e7",
    title: "Stand-up: Kacper Ruciński — Nowy program",
    category: "performing_arts",
    venue: { id: "v7", name: "Klub Stodoła", address: "Bukowska 16" },
    imageUrl: "/mock/event-7.jpg",
    date: "Czw, 29 maja",
    time: "19:30",
    startDate: "2026-05-29T19:30:00",
    priceFrom: 95,
    lat: 52.4055,
    lng: 16.9055,
    description:
      "Premiera nowego materiału jednego z najpopularniejszych polskich komików.",
    badges: [],
    city: "poznan",
  },
  {
    id: "e8",
    title: "Pierogi Festival — degustacje z całej Polski",
    category: "food_drink",
    venue: { id: "v8", name: "Plac Wolności", address: "Plac Wolności" },
    imageUrl: "/mock/event-8.jpg",
    date: "Sob–Nd, 24–25 maja",
    time: "12:00–22:00",
    startDate: "2026-05-24T12:00:00",
    priceFrom: 0,
    lat: 52.4076,
    lng: 16.9285,
    description: "24 odmiany pierogów od 18 restauracji. Warsztaty lepienia.",
    badges: ["free", "recur"],
    city: "poznan",
  },
  {
    id: "e9",
    title: "Hamlet — reż. Krystian Lupa",
    category: "performing_arts",
    venue: { id: "v9", name: "Teatr Polski", address: "27 Grudnia 8/10" },
    imageUrl: "/mock/event-9.jpg",
    date: "Pt, 30 maja",
    time: "19:00",
    startDate: "2026-05-30T19:00:00",
    priceFrom: 75,
    lat: 52.4068,
    lng: 16.9305,
    description:
      "Reinterpretacja Hamleta w reżyserii Krystiana Lupy. Spektakl trwa 4 godziny.",
    badges: [],
    city: "poznan",
  },
  {
    id: "e10",
    title: "AI Summit Poznań — startup pitch night",
    category: "business",
    venue: {
      id: "v10",
      name: "Concordia Design",
      address: "Zwierzyniecka 3",
    },
    imageUrl: "/mock/event-10.jpg",
    date: "Śr, 28 maja",
    time: "18:00",
    startDate: "2026-05-28T18:00:00",
    priceFrom: 0,
    lat: 52.4095,
    lng: 16.9355,
    description:
      "12 startupów AI prezentuje się przed inwestorami i mentorami.",
    badges: ["free"],
    city: "poznan",
  },
  {
    id: "e11",
    title: "Noc Muzeów 2026",
    category: "arts_culture",
    venue: {
      id: "v11",
      name: "Cała Poznań",
      address: "Różne lokalizacje",
    },
    imageUrl: "/mock/event-11.jpg",
    date: "Sob, 24 maja",
    time: "18:00–02:00",
    startDate: "2026-05-24T18:00:00",
    priceFrom: 0,
    lat: 52.412,
    lng: 16.941,
    description: "32 muzea i galerie otwarte przez całą noc.",
    badges: ["free", "live"],
    city: "poznan",
  },
  {
    id: "e12",
    title: "Yoga w Parku Sołackim — sunrise flow",
    category: "wellness",
    venue: { id: "v12", name: "Park Sołacki", address: "Wielka Solna" },
    imageUrl: "/mock/event-12.jpg",
    date: "Nd, 25 maja",
    time: "07:00",
    startDate: "2026-05-25T07:00:00",
    priceFrom: 25,
    lat: 52.4175,
    lng: 16.912,
    description: "Cotygodniowa sesja porannej yogi na otwartej trawie.",
    badges: ["recur"],
    city: "poznan",
  },
  // Krakow events
  {
    id: "e13",
    title: "Kraków Jazz Autumn — preview",
    category: "music",
    venue: {
      id: "v13",
      name: "Piwnica pod Baranami",
      address: "Rynek Główny 27",
    },
    imageUrl: "/mock/event-1.jpg",
    date: "Sob, 24 maja",
    time: "20:00",
    startDate: "2026-05-24T20:00:00",
    priceFrom: 120,
    lat: 50.0617,
    lng: 19.9373,
    description: "Wieczór jazzowy w legendarnej Piwnicy pod Baranami.",
    badges: [],
    city: "krakow",
  },
  {
    id: "e14",
    title: "Warsztaty ceramiki dla początkujących",
    category: "education",
    venue: {
      id: "v14",
      name: "Pracownia Ceramiczna",
      address: "Józefińska 8",
    },
    imageUrl: "/mock/event-4.jpg",
    date: "Nd, 25 maja",
    time: "10:00",
    startDate: "2026-05-25T10:00:00",
    priceFrom: 150,
    lat: 50.0458,
    lng: 19.9518,
    description: "3-godzinne warsztaty ceramiki — od gliny do gotowego kubka.",
    badges: [],
    city: "krakow",
  },
  {
    id: "e15",
    title: "Rodzinny piknik na Błoniach",
    category: "family",
    venue: { id: "v15", name: "Błonia", address: "Błonia Krakowskie" },
    imageUrl: "/mock/event-8.jpg",
    date: "Nd, 25 maja",
    time: "11:00",
    startDate: "2026-05-25T11:00:00",
    priceFrom: 0,
    lat: 50.0587,
    lng: 19.9145,
    description:
      "Animacje dla dzieci, food trucki, kino plenerowe pod gwiazdami.",
    badges: ["free"],
    city: "krakow",
  },
];
